/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ICbd4Zhpx0p
 */
import { CalendarIcon, ClockIcon, InfoIcon, PlusIcon } from "lucide-react";
import Link from "next/link";

export function AppBar() {
  return (
    <div className="flex lg:flex-row bg-brand text-white border-t w-full fixed bottom-0 h-14">
      <div className="flex-1 flex items-center justify-center py-4 lg:py-6 border-r lg:border-r-0 lg:border-b cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700">
        <Link
          className="text-center flex items-center flex-col gap-[0.8rem]"
          href="/bookings"
        >
          <CalendarIcon />
        </Link>
      </div>
      <div className="flex-1 flex items-center justify-center py-4 lg:py-6 border-r lg:border-r-0 lg:border-b cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700">
        <Link
          className="text-center flex items-center  flex-col gap-[0.8rem]"
          href="/schedules"
        >
          <ClockIcon />
        </Link>
      </div>
      <div className="flex-1 flex items-center justify-center py-4 lg:py-6 border-r lg:border-r-0 lg:border-b cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700">
        <Link
          className="text-center flex items-center  flex-col gap-[0.8rem]"
          href="/"
        >
          <PlusIcon />
        </Link>
      </div>
      <div className="flex-1 flex items-center justify-center py-4 lg:py-6 cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700">
        <Link
          className="text-center flex items-center  flex-col gap-[0.8rem]"
          href="/all"
        >
          <InfoIcon />
        </Link>
      </div>
    </div>
  );
}
