/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ICbd4Zhpx0p
 */
import { CalendarIcon, ClockIcon, InfoIcon, PlusIcon } from "lucide-react";
import Link from "next/link";

export function AppBar() {
  return (
    <div className="flex lg:flex-row bg-white text-black border-t-4 border-t-black w-full fixed bottom-0 h-14">
      <Link
        href="/bookings"
        className="flex-1 flex items-center justify-center py-4 lg:py-6 border-r lg:border-r-0 lg:border-b cursor-pointer "
      >
        <div className="text-center flex items-center flex-col gap-[0.8rem]">
          <CalendarIcon />
        </div>
      </Link>
      <Link
        href="/schedules"
        className="flex-1 flex items-center justify-center py-4 lg:py-6 border-r lg:border-r-0 lg:border-b cursor-pointer "
      >
        <div className="text-center flex items-center  flex-col gap-[0.8rem]">
          <ClockIcon />
        </div>
      </Link>
      <Link
        href="/"
        className="flex-1 flex items-center justify-center py-4 lg:py-6 border-r lg:border-r-0 lg:border-b cursor-pointer"
      >
        <div className="text-center flex items-center  flex-col gap-[0.8rem]">
          <PlusIcon />
        </div>
      </Link>
    </div>
  );
}
