"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j7QQWsTHwh8
 */
import { Button } from "@/components/ui/button";
import { useEffect, useState } from "react";

export function Header() {
  const [email, setEmail] = useState("");
  useEffect(() => {
    const email = window.localStorage.getItem("email");
    if (email) setEmail(email);
  }, []);
  return (
    <header
      key="1"
      className="h-14 flex items-center justify-between px-4 bg-black shadow-md text-white"
    >
      <div className="text-sm text-gray-600 dark:text-gray-400">{email}</div>
      <Button
        className="p-2"
        variant="outline"
        onClick={() => {
          window.localStorage.removeItem("email");
          window.localStorage.removeItem("password");
          window.location.reload();
        }}
      >
        Switch User
      </Button>
    </header>
  );
}


